### ISSUE TITLE
Add JAvascript Projects

### ISSUE THREAD

**Issue by harshvardhan614** [Izroth404/Hacktoberfest2022#75]

**Comment by harshvardhan614** [comment]
Hi @Izroth404  Can I Add my JAvascript projects in this repository?

**Comment by Izroth404** [comment]
~~sure!!  just don't forget to create a separate folder for it~~

**Comment by Izroth404** [comment]
sure!!  just don't forget to create a separate folder for it @harshvardhan614

**Comment by harshvardhan614** [comment]
Ohhkk!
I create a new folder for my Project.
pls merge my PR #76

**Comment by Izroth404** [comment]
PR is merged.
